name: cloudflared
services:
  cloudflared:
    command:
    - tunnel
    - --no-autoupdate
    - run
    - --token
    - $CLOUDFLARED_TOKEN
    image: cloudflare/cloudflared:latest
    networks:
      erebos-net: null
    restart: unless-stopped
networks:
  erebos-net:
    name: erebos-net
    external: true
