name: Terraform Format Check

on:
  pull_request:
    branches:
      - main

jobs:
    call-format-check:
        uses: RedNoodlesOrg/rednet-actions-workflows/.github/workflows/terraform-format-check.yml@main
